name: funnel
dim: 10
has_entropy: False

fn:
  _target_: targets.funnel.Funnel
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: [-30, 30]

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 1.
  step_size: 1e-2

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: .1

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.001, 0.1]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 1.

smc_rebuttal:
  initial_scale: 10.0
  target_ess: 0.99
  hmc_step_size: [0.1, 0.2]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 1.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 1.
  step_size: 1e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 1.
  step_size: 1e-3 #5e-4
  max_diffusion: 6.
pis: # Path Integral Sampler
  max_diffusion: 4. # Divided by 4 roughly gives the initial scale
  step_size: #5e-4

dis: # Time-reversed Diffusion Sampler
  initial_scale: 1.
  step_size: 1e-3

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 1. 
  initial_scale: 1.
  step_size: 5e-4

gbs:  # General Schroedinger Bridge
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  initial_scale: 1.
  step_size: 5e-4
  eps: 1e-3

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  max_diffusion: 10.
  initial_scale: 1.
  step_size: 5e-4

############# HYPERPARAMETERS USED IN OUR PAPER #############
# We strictly follow the settings of the SCLD paper, except that
# we report which yields better results between using or not using
# the multistep learning rate scheduling.

scld_cmcd_kl:
  initial_scale: 1.
  max_diffusion: 10. 
  model_type: StateTimeNetwork
  step_size: 1e-3
  annealing_step_size: 1e-2
  milestones: [20000, 30000]

scld_cmcd_lv:
  initial_scale: 1.
  max_diffusion: 1. 
  model_type: StateTimeNetwork
  step_size: 1e-3
  annealing_step_size: 1e-2
  milestones: [20000, 30000]

scld:
  initial_scale: 1.
  max_diffusion: 1. 
  step_size: 1e-3
  annealing_step_size: 1e-2
  n_sub_traj: 128
  n_sim: 3000
  milestones: [1500, 2250]

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  num_hid: 64