name: gaussian_mixture40
num_components: 40
dim: 50
has_entropy: True
plot_range: 60

fn:
  _target_: targets.gmm40.GMM40
  num_components: ${target.num_components}
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: None
  loc_scaling: 40
  scale_scaling: 1

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 40.
  step_size: 1e-2

nfvi: # Normalizing Flow Variational Inference
  initial_scale: 40.
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 40.

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.2, 0.001]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 40.

smc_rebuttal:
  initial_scale: 40 #0.1
  target_ess: 0.99
  hmc_step_size: [0.01, 0.001]

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 40.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 40.
  step_size: 1e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 40.
  step_size: 1e-4 #5e-4
  max_diffusion: 6.
pis: # Path Integral Sampler
  max_diffusion: 160. # Divided by 4 roughly gives the initial scale
  step_size: 5e-4

dis: # Time-reversed Diffusion Sampler
  initial_scale: 40.
  step_size: 1e-4

cmcd:  # Controlled Monte Carlo Diffusions
  max_diffusion: 20.
  initial_scale: 40.
  step_size: 1e-4

gsb:  # General Schroedinger Bridge
  max_diffusion: 10.
  initial_scale: 40.
  step_size: 5e-4

ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  initial_scale: 40.
  step_size: 5e-4
  eps: 1e-2

od_langevin:  # Overdamped Langevin Methods (ULA/MCD/CMCD)
  max_diffusion: 40.
  initial_scale: 40.
  step_size: 5e-4

############# HYPERPARAMETERS USED IN OUR PAPER #############
# We strictly follow the settings of the SCLD paper, except that
# we report which yields better results between using or not using
# the multistep learning rate scheduling.

scld_cmcd_kl:
  initial_scale: 40.
  max_diffusion: 10.
  model_type: StateTimeNetwork
  step_size: 1e-4
  annealing_step_size: 1e-2
  milestones: [20000, 30000]

scld_cmcd_lv:
  initial_scale: 40.
  max_diffusion: 20.
  model_type: PISGRADNet
  step_size: 1e-4
  annealing_step_size: 1e-2
  milestones: [20000, 30000]

scld:
  initial_scale: 40.
  max_diffusion: 20.
  step_size: 1e-3
  annealing_step_size: 1e-3
  n_sub_traj: 4
  n_sim: 25000
  milestones: [12500, 18750]

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  num_hid: 64